#!/bin/bash
#SBATCH -J SAMPSORT
#SBATCH -o SAMPSORT.o%j
#SBATCH -n 16
#SBATCH -p normal
#SBATCH -t 00:30:00
#SBATCH --mail-user=mcdonald@cims.nyu.edu
#SBATCH --mail-type=begin
#SBATCH --mail-type=end
#SBATCH -A TG-ASC150003

ibrun ./ssort


